### ISSUE TITLE
Migration error log messages when upgrading to 4.2.2 from 3.6.6

### ISSUE THREAD

**Issue by zakx** [dominikamann/oekofen-pellematic-compact#169]
For reference, I had the following warnings/errors in my log after upgrading to 4.2.2 from 3.6.6.

```
Feb 15 22:19:37 homeassistant homeassistant[671]: 2026-02-15 22:19:37.584 WARNING (MainThread) [custom_components.oekofen_pellematic_compact] Migration V1→V2: Failed to auto-detect config, using defaults: too many values to unpack (expected 2)
Feb 15 22:19:37 homeassistant homeassistant[671]: 2026-02-15 22:19:37.588 WARNING (MainThread) [custom_components.oekofen_pellematic_compact] Setup Pellematic: CONF_CHARSET, CONF_API_SUFFIX, or CONF_OLD_FIRMWARE missing! Attempting auto-detection...
Feb 15 22:19:37 homeassistant homeassistant[671]: 2026-02-15 22:19:37.600 ERROR (SyncWorker_7) [custom_components.oekofen_pellematic_compact] Failed to fetch with '?': HTTP Error 401: Unauthorized
Feb 15 22:19:37 homeassistant homeassistant[671]: 2026-02-15 22:19:37.604 ERROR (MainThread) [custom_components.oekofen_pellematic_compact] Setup Pellematic: Failed to auto-detect config, using defaults: HTTP Error 401: Unauthorized
Feb 15 22:19:37 homeassistant homeassistant[671]: 2026-02-15 22:19:37.623 ERROR (MainThread) [custom_components.oekofen_pellematic_compact] Failed to fetch Pellematic data: HTTP Error 401: Unauthorized
Feb 15 22:19:37 homeassistant homeassistant[671]: 2026-02-15 22:19:37.630 WARNING (MainThread) [custom_components.oekofen_pellematic_compact] Entity ID migration failed (non-critical): 'HomeAssistant' object has no attribute 'components'
```

Let me know if I can provide anything else to help with that, but maybe the errors themselves help already.

Other than that, I noticed that some binary states changed from "1_on" / "0_off" to "1_ein" / "0_aus" which broke my manual hot water trigger. Would be good to note that in the release notes I guess.
